import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { promises as fs } from 'fs';
import path from 'path';
import os from 'os';
import { InitCommand } from '../../src/core/init.js';

describe('InitCommand', () => {
  let tmpDir: string;

  beforeEach(async () => {
    tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'openlog-test-'));
  });

  afterEach(async () => {
    await fs.rm(tmpDir, { recursive: true, force: true });
  });

  describe('execute (--tools none)', () => {
    it('creates openlog/ directory structure', async () => {
      const cmd = new InitCommand({ tools: 'none' });
      await cmd.execute(tmpDir);

      const openlogDir = path.join(tmpDir, 'openlog');
      expect(await exists(openlogDir)).toBe(true);
      expect(await exists(path.join(openlogDir, 'specs'))).toBe(true);
      expect(await exists(path.join(openlogDir, 'changes'))).toBe(true);
      expect(await exists(path.join(openlogDir, 'project.md'))).toBe(true);
    });

    it('project.md contains project name', async () => {
      const cmd = new InitCommand({ tools: 'none' });
      await cmd.execute(tmpDir);

      const content = await fs.readFile(
        path.join(tmpDir, 'openlog', 'project.md'),
        'utf8',
      );
      const dirName = path.basename(tmpDir);
      expect(content).toContain(`# ${dirName}`);
    });
  });

  describe('execute (--tools claude)', () => {
    it('creates .claude/ skills and commands', async () => {
      const cmd = new InitCommand({ tools: 'claude' });
      await cmd.execute(tmpDir);

      expect(await exists(path.join(tmpDir, '.claude', 'skills'))).toBe(true);
      expect(await exists(path.join(tmpDir, '.claude', 'commands', 'oplg'))).toBe(true);

      const applySkill = path.join(tmpDir, '.claude', 'skills', 'openlog-apply', 'SKILL.md');
      expect(await exists(applySkill)).toBe(true);
      const skillContent = await fs.readFile(applySkill, 'utf8');
      expect(skillContent).toContain('name: openlog-apply');

      const applyCmd = path.join(tmpDir, '.claude', 'commands', 'oplg', 'apply.md');
      expect(await exists(applyCmd)).toBe(true);
    });
  });

  describe('execute (--tools github-copilot)', () => {
    it('creates .github/prompts/ commands (no skills)', async () => {
      const cmd = new InitCommand({ tools: 'github-copilot' });
      await cmd.execute(tmpDir);

      const promptFile = path.join(tmpDir, '.github', 'prompts', 'oplg-apply.prompt.md');
      expect(await exists(promptFile)).toBe(true);

      const skillsDir = path.join(tmpDir, '.github', 'skills');
      expect(await exists(skillsDir)).toBe(false);
    });
  });

  describe('idempotency', () => {
    it('repeated execution does not change content (all unchanged)', async () => {
      const cmd = new InitCommand({ tools: 'all' });
      await cmd.execute(tmpDir);

      const applySkill = path.join(tmpDir, '.claude', 'skills', 'openlog-apply', 'SKILL.md');
      const contentBefore = await fs.readFile(applySkill, 'utf8');

      await cmd.execute(tmpDir);

      const contentAfter = await fs.readFile(applySkill, 'utf8');
      expect(contentAfter).toBe(contentBefore);
    });
  });

  describe('--force', () => {
    it('force mode regenerates project.md', async () => {
      const cmd = new InitCommand({ tools: 'none' });
      await cmd.execute(tmpDir);

      const projectMdPath = path.join(tmpDir, 'openlog', 'project.md');
      await fs.writeFile(projectMdPath, '# custom content\n', 'utf8');

      const forceCmd = new InitCommand({ tools: 'none', force: true });
      await forceCmd.execute(tmpDir);

      const content = await fs.readFile(projectMdPath, 'utf8');
      expect(content).not.toContain('# custom content');
      expect(content).toContain('Generated by');
    });
  });

  describe('parseToolsArg error handling', () => {
    it('throws error for invalid tool name', async () => {
      const cmd = new InitCommand({ tools: 'invalid-tool' });
      await expect(cmd.execute(tmpDir)).rejects.toThrow('Unknown tools');
    });
  });

  describe('auto-creates target path when it does not exist', () => {
    it('creates non-existent target directory', async () => {
      const nested = path.join(tmpDir, 'deep', 'nested', 'project');
      const cmd = new InitCommand({ tools: 'none' });
      await cmd.execute(nested);

      expect(await exists(path.join(nested, 'openlog'))).toBe(true);
    });
  });
});

async function exists(target: string): Promise<boolean> {
  try {
    await fs.access(target);
    return true;
  } catch {
    return false;
  }
}
